CREATE TABLE ORDERS(

ID NUMBER,
CONSTRAINT ORDER_ID PRIMARY KEY (ID),
PRODUCT_NAME NVARCHAR2(20),
PRICE NUMBER,
DATE_ORDER TIMESTAMP,
DATE_CONFIRMED TIMESTAMP


);

UPDATE ORDERS SET PRICE = 130 WHERE ID = 1002;

SELECT PRODUCT_NAME, AVG(PRICE) FROM ORDERS
GROUP BY product_name;