CREATE TABLE MOVIE (
ID NUMBER,
CONSTRAINT PK PRIMARY KEY(ID),
TITLE NVARCHAR2(50) UNIQUE,
DIRECTOR NVARCHAR2(50) UNIQUE,
YEAR NUMBER CHECK(YEAR >=1900 AND YEAR <= 2019),
LENGTH_MINS NUMBER CHECK (LENGTH_MINS BETWEEN 10 AND 100)
);

CREATE TABLE MOVIE_STAT (
MOVIE_ID NUMBER,
CONSTRAINT MOVIESTAT_PK PRIMARY KEY(MOVIE_ID),
RATING DECIMAL(2, 1) CHECK (RATING BETWEEN 1 AND 10),
DOMESTIC_SALES NUMBER,
INTERNATIONAL_SALES NUMBER
);

SELECT * FROM MOVIE WHERE (DIRECTOR = 'Nolan');

SELECT * FROM MOVIE WHERE (TITLE LIKE 'batman');

ALTER TABLE MOVIE
MODIFY TITLE NOT NULL;

ALTER TABLE MOVIE
DISABLE CONSTRAINT SYS_C003950;

SELECT DOMESTIC_SALES FROM MOVIE_STAT
WHERE EXISTS (SELECT DIRECTOR FROM movie WHERE id = MOVIE_STAT.MOVIE_ID AND DIRECTOR = 'Nolan');


select * from movie order by year asc;

SELECT INTERNATIONAL_SALES FROM MOVIE_STAT ORDER BY international_sales DESC;